const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(),{sections,acts,normalize,makeStory,markdown}=StoryModel;
let story=normalize(window.exampleStory),tab='overview',dirty=false,viewMode='list',volumeFilter='',saveAction,modalInitial='';
const SF=new Set(['basis','spacetime','phenomenon','explanation','truth','knowledge']);
function visibleFields(k){return sections[k].fields.filter(f=>story.mode==='科幻'||!SF.has(f.key)||hasField(k,f.key))}
function hasField(k,key){return sections[k].single?!!story[k][key]:story[k].some(x=>x[key])}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').style.display='none',3500)}
function changed(){dirty=true;$('#foot').textContent='有未导出的修改 · 保存草稿以便下次继续'}
function field(f,value='',context=tab){const id='f-'+f.key,baseOptions=f.key==='act'?acts(story):f.options,options=f.type==='select'&&value&&!baseOptions.includes(value)?[value,...baseOptions]:baseOptions;const required=f.key==='title'?' required':'';return `<div class="form-field ${f.type==='textarea'?'wide':''}"><label for="${id}">${f.label}${required?' *':''}</label>${f.hint?`<p class="field-hint">${esc(f.hint)}</p>`:''}${f.type==='select'?`<select id="${id}" name="${f.key}">${options.map(v=>`<option ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`:f.type==='input'?`<input id="${id}" name="${f.key}" value="${esc(value)}"${required} maxlength="500">`:`<textarea id="${id}" name="${f.key}" rows="3">${esc(value)}</textarea>`}</div>`}
function formData(){return Object.fromEntries(new FormData($('#form')))}
function closeModal(){if(JSON.stringify(formData())!==modalInitial&&!confirm('放弃这次尚未提交的编辑？'))return;$('#modal').close()}
function openModal(title,html,save,del){$('#modal-title').textContent=title;$('#fields').innerHTML=html;$('.danger')?.remove();if(del){const b=document.createElement('button');b.type='button';b.className='danger';b.textContent='删除此项';b.onclick=()=>{if(confirm('确定删除这一项？关联位置中的文字将保留，请按需调整。')){del();$('#modal').close();changed();render()}};$('.modal-actions').prepend(b)}saveAction=save;$('#modal').showModal();modalInitial=JSON.stringify(formData())}
$('#form').onsubmit=e=>{e.preventDefault();const d=formData();if('title'in d&&!d.title.trim()){toast('请填写名称');$('#f-title').focus();return}for(const k of Object.keys(d))d[k]=d[k].trim();saveAction(d);$('#modal').close();changed();render();toast('已更新，请保存草稿文件')};$('#close').onclick=$('#cancel').onclick=closeModal;$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal()});
function render(){document.title=story.title+' · 叙事间';$('#book-title').textContent=story.title;$('#crumb-title').textContent=story.title;$('#genre').textContent=story.genre||'未设定题材';$('#structure').textContent=story.mode+' · '+story.structure;$('#premise').textContent=story.premise||'点击「编辑作品信息」，写下你的一句话故事。';$('#nav').innerHTML=Object.entries(sections).map(([k,v])=>`<button data-tab="${k}" class="${tab===k?'active':''}" aria-current="${tab===k?'page':'false'}"><span class="nav-icon">${v.icon}</span>${v.name}<span class="nav-count">${v.single?Object.values(story[k]).filter(Boolean).length+'/'+v.fields.length:story[k].length}</span></button>`).join('');$('#stats').innerHTML=[['outline','章节'],['characters','人物'],['plot','剧情线'],['foreshadow','待回收伏笔']].map(([k,label])=>`<button class="stat" data-tab="${k}"><div class="stat-icon">${sections[k].icon}</div><div><b>${k==='foreshadow'?story[k].filter(x=>x.status!=='已回收').length:story[k].length}</b><small>${label}</small></div></button>`).join('');const v=sections[tab];$('#view-title').textContent=v.name;$('#view-desc').textContent=v.desc;$('#add').textContent=v.single?'编辑'+v.name:'＋ 添加'+({outline:'章节',characters:'人物',world:'设定',plot:'剧情线',nodes:'节点',foreshadow:'伏笔'}[tab]);if(v.single){$('#content').innerHTML=`${tab==='overview'?guide():''}<div class="detail-grid">${v.fields.map(f=>`<button class="detail-block" data-single="${f.key}"><span>${f.label}</span><p class="${story[tab][f.key]?'':'unfilled'}">${esc(story[tab][f.key]||f.hint||'点击填写')}</p></button>`).join('')}</div>`;return}const allItems=story[tab],items=tab==='outline'&&volumeFilter?allItems.filter(x=>x.volume===volumeFilter):allItems;let toolbar=tab==='outline'?`<div class="view-controls"><label class="volume-filter">分卷 <select id="volume-filter"><option value="">全部章节（${allItems.length}）</option>${[...new Set(allItems.map(x=>x.volume).filter(Boolean))].map(v=>`<option value="${esc(v)}" ${v===volumeFilter?'selected':''}>${esc(v)}</option>`).join('')}</select></label><span>上下调整完整章节顺序</span><div><button data-view="board" aria-pressed="${viewMode==='board'}">结构看板</button><button data-view="list" aria-pressed="${viewMode==='list'}">章节列表</button></div></div>`:'';if(!items.length){$('#content').innerHTML=toolbar+`<div class="empty">${tab==='world'?'记录第一条世界规则，让人物有真实的限制。':'这里还是一张白纸，添加第一项开始构思。'}<br><button style="margin-top:18px" data-create>＋ 添加${v.name}</button></div>`;return}if(tab==='outline'&&viewMode==='board'){$('#content').innerHTML=toolbar+`<div class="board upgraded-board">${acts(story).map((a,i)=>`<div class="column"><div class="column-head"><i class="act-dot"></i>${i+1} · ${a}<span>${items.filter(x=>x.act===a).length} 章</span></div>${items.filter(x=>x.act===a).map(x=>card(x,allItems.indexOf(x))).join('')}<button class="column-add" data-act="${a}">＋ 添加章节</button></div>`).join('')}</div>`}else $('#content').innerHTML=toolbar+`<div class="${tab==='plot'||tab==='outline'?'timeline':'grid'}">${items.map(x=>card(x,allItems.indexOf(x))).join('')}</div>`}
function guide(){const checks=[['synopsis',!!story.synopsis.ending,'写明故事结局'],['characters',!!story.characters.length,'设定主要人物'],['world',!!story.world.length,'建立世界规则'],['outline',story.outline.some(x=>x.goal&&x.result),'补齐章节目标与结果']];return `<div class="guide"><div><b>从总纲到正文</b><span>${checks.filter(x=>x[1]).length} / 4 项基础准备</span></div><div class="guide-steps">${checks.map(([k,done,label])=>`<button data-tab="${k}" class="${done?'done':''}">${done?'✓':'○'} ${label}</button>`).join('')}</div><p>这些提示帮助检查遗漏，不代表作品质量评分。</p></div>`}
function card(x,i){const desc=x.body||x.goal||x.want||'尚未填写内容，点击继续构思';const tags=[x.role||x.tag,x.status,x.position||x.plant].filter(Boolean);return `<article class="entry"><button class="card" data-id="${x.id}" aria-label="编辑${esc(x.title)}">${tab==='characters'?`<div class="person-initial">${esc(x.title.slice(0,1))}</div>`:''}<div class="card-top"><span>${esc(tags[0]||'待构思')}</span><span>${esc(tags[1]||'点击编辑')}</span></div><h3>${esc(x.title)}</h3><p>${esc(desc)}</p><div class="card-bottom">${x.people?`<span class="tag">${esc(x.people)}</span>`:''}${tab==='outline'&&x.pov?`<span>视角 · ${esc(x.pov)}</span>`:''}${tab==='foreshadow'?`<span>埋设 ${esc(x.plant||'待定')} → 回收 ${esc(x.reveal||'待定')}</span>`:''}${tab==='nodes'?`<span>${esc(x.position||'位置待定')}</span>`:''}</div></button><div class="entry-actions"><button data-move="${x.id}" data-dir="-1" ${i===0?'disabled':''} aria-label="上移${esc(x.title)}">↑</button><button data-move="${x.id}" data-dir="1" ${i===story[tab].length-1?'disabled':''} aria-label="下移${esc(x.title)}">↓</button><button class="entry-edit" data-id="${x.id}">编辑 ↗</button></div></article>`}
function edit(id,act,focusKey){const k=tab,v=sections[k],x=v.single?story[k]:story[k].find(x=>x.id===id)||{act:act||acts(story)[0]};const html=visibleFields(k).map(f=>field(f,x[f.key]||'')).join('');openModal((v.single||id?'编辑':'添加')+v.name,html,d=>{if(v.single||id)Object.assign(x,d);else story[k].push({id:uid(),...d})},!v.single&&id?()=>story[k]=story[k].filter(x=>x.id!==id):null);if(focusKey)$('#f-'+focusKey)?.focus()}
const metaFields=[{key:'title',label:'作品名称',type:'input'},{key:'genre',label:'题材',hint:'科幻、悬疑、历史、言情……',type:'input'},{key:'mode',label:'创作模式',type:'select',options:['通用','科幻']},{key:'premise',label:'一句话故事',hint:'谁为了什么，在什么阻碍下作出了什么选择？',type:'textarea'}];
function settings(isNew){const s=isNew?{title:'',genre:'',mode:'通用',premise:'',structure:'三幕式'}:story;let fields=metaFields;if(isNew)fields=[...fields,{key:'structure',label:'故事结构',type:'select',options:['三幕式','起承转合','科幻五阶段']}];openModal(isNew?'新建故事':'编辑作品信息',fields.map(f=>field(f,s[f.key]||'')).join('')+`<p class="helper wide">${isNew?'根据所选结构建立空白章节。模板提供写作框架，不自动生成正文。新建会替换当前故事，请先保存草稿。':'科幻模式增加科学依据、时空约束、证据与认知字段。切换模式保留已有内容。'}</p>`,d=>{if(isNew){story=makeStory(d);if(d.structure==='科幻五阶段')story.mode='科幻';tab='overview';volumeFilter=''}else Object.assign(story,d)})}
function navigate(e){const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;render()}}
$('#nav').onclick=$('#stats').onclick=navigate;$('#content').onclick=e=>{navigate(e);const b=e.target.closest('[data-id]'),a=e.target.closest('[data-act]'),s=e.target.closest('[data-single]'),m=e.target.closest('[data-move]'),v=e.target.closest('[data-view]');if(b)edit(b.dataset.id);if(a)edit(null,a.dataset.act);if(s)edit(null,null,s.dataset.single);if(e.target.closest('[data-create]'))edit();if(v){viewMode=v.dataset.view;render()}if(m){const arr=story[tab],i=arr.findIndex(x=>x.id===m.dataset.move),j=i+Number(m.dataset.dir);if(j>=0&&j<arr.length){[arr[i],arr[j]]=[arr[j],arr[i]];changed();render()}}};$('#add').onclick=()=>edit();$('#settings').onclick=()=>settings(false);$('#new').onclick=()=>{if(!dirty||confirm('当前有未导出的修改。继续新建？取消后可先保存草稿。'))settings(true)};
function download(text,type,ext){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=story.title.replace(/[\\/:*?"<>|]/g,'_')+ext;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#backup').onclick=()=>{download(JSON.stringify({version:2,story},null,2),'application/json','.json');dirty=false;$('#foot').textContent='已导出完整草稿 · 可导入继续编辑';toast('草稿已导出，包含全部设定与章节')};$('#export').onclick=()=>{download(markdown(story),'text/markdown;charset=utf-8','.md');toast('完整大纲已导出；可编辑备份请使用「保存草稿」')};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10e6)throw Error('草稿文件超过10MB');const raw=JSON.parse(await f.text());if(![1,2].includes(raw.version))throw Error('不支持的草稿版本');const next=normalize(raw.story);if(dirty&&!confirm('导入将替换当前未导出的修改，继续？'))return;story=next;dirty=false;tab='overview';volumeFilter='';render();$('#foot').textContent=raw.version===1?'旧版草稿已兼容导入 · 保存后为新版格式':'已导入完整草稿';toast('草稿已恢复，新增板块可继续填写')}catch(err){toast('无法导入：'+(err instanceof SyntaxError?'请选择有效的叙事间草稿文件':err.message))}finally{e.target.value=''}};
$('#content').addEventListener('change',e=>{if(e.target.id==='volume-filter'){volumeFilter=e.target.value;render()}});
$('#restore-example').onclick=()=>{if(!confirm('恢复示例故事会替换当前页面的内容；如有修改，请先保存草稿。'))return;story=normalize(JSON.parse(JSON.stringify(window.exampleStory)));tab='overview';volumeFilter='';dirty=false;render();$('#foot').textContent='已恢复通用示例故事';toast('示例故事已恢复')};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_story_plan',description:'Read all current story planning sections including science rules, foreshadowing and chapters.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw Error('Expected empty object');return JSON.parse(JSON.stringify(story))}})).catch(()=>{})}catch{}}
render();
