(function(root){
const f=(key,label,hint='',type='textarea',options=[])=>({key,label,hint,type,options});
const field={title:f('title','名称','','input'),body:f('body','内容','描述具体发生的事情与原因'),people:f('people','关联人物','与人物档案中的名字保持一致','input'),status:f('status','状态','','select',['待完善','已构思','已完成'])};
const sections={
 overview:{name:'作品概况',icon:'◈',desc:'先写清你要讲什么，以及为什么要讲。',single:true,fields:[f('audience','目标读者','谁会关心这个故事？','input'),f('length','预计篇幅','例如：20万字，40章','input'),f('tone','整体基调','克制、悬疑、恢宏、温暖……','input'),f('pov','叙述视角','第一人称、第三人称限知、多视角……','input'),f('theme','主题问题','让人物用选择回答的问题'),f('conflict','核心冲突','谁想要什么，什么力量阻止他？'),f('hook','主要看点','设定、关系或情节的独特之处')]},
 world:{name:'世界设定',icon:'◎',desc:'给故事划定边界，让规则真正约束人物。',fields:[field.title,f('tag','设定类别','','select',['时空背景','社会制度','地点与势力','科学技术','文明设定','其他规则']),field.body,f('limits','限制条件','什么绝对做不到？'),f('cost','代价与失败方式','使用成本、资源消耗、失效条件'),f('impact','社会与生活影响','谁受益，谁承担风险？'),f('basis','科学依据与虚构边界','区分已知科学、合理外推、明确虚构'),f('spacetime','时间与空间约束','距离、航行、通信延迟与时间尺度'),field.status]},
 characters:{name:'人物关系',icon:'♙',desc:'动机推动行动，选择改变关系。',fields:[field.title,f('role','角色定位','','select',['主角','关键配角','对手','其他人物']),field.body,f('want','目标与动机','他想得到什么，为什么重要？'),f('stakes','失败风险','失败会失去什么？'),f('ability','能力与资源','他凭什么行动？'),f('fear','弱点与盲点','什么会让他判断失误？'),f('contradiction','内在矛盾与底线','哪些信念或欲望彼此冲突？'),f('choice','关键选择','压力最大时的决定'),f('arc','人物弧线','成长、堕落，或付出代价坚持信念'),f('relation','人物关系','对象 → 当前关系 → 变化原因')]},
 synopsis:{name:'故事总纲',icon:'▤',desc:'写明真相与结局，用因果连接整个故事。',single:true,fields:[f('opening','起因与初始处境','日常如何被打破？'),f('decision','目标与关键决定','主角为什么不能置身事外？'),f('escalation','行动与冲突升级','行动如何带来新的阻碍？'),f('turn','重大转折与真相','新信息改变了什么前提？'),f('climax','高潮与最终选择','主角在什么两难之间作出选择？'),f('ending','结局与代价','冲突如何结束？谁失去或得到什么？'),f('aftermath','余波与主题回应','世界和人物留下了什么变化？')]},
 plot:{name:'剧情线',icon:'⌁',desc:'让主线与支线有各自的目标，也有交汇的理由。',fields:[field.title,f('tag','剧情线类型','','select',['主线','支线','人物关系线']),f('goal','目标与起点','这一条线从哪里开始，要解决什么？'),field.body,field.people,f('intersection','与其他线的交汇','在哪个事件相互影响？'),f('consequence','结果与主线作用','改变主线、人物或世界的什么？'),field.status]},
 nodes:{name:'关键节点',icon:'◇',desc:'记录每一次不可逆的变化，以及人物对真相的认识。',fields:[field.title,f('tag','节点类型','','select',['引发事件','关键决定','转折','中点','危机','高潮','结局','伏笔']),f('position','发生位置','卷、章或故事时间','input'),field.body,field.people,f('cause','前置原因','哪件事导致它发生？'),f('change','改变与代价','目标、处境、关系或选择发生什么变化？'),f('phenomenon','观测现象与证据','人物实际看见或测得什么？'),f('explanation','当时的解释','人物为什么这样理解？'),f('truth','真实机制','作者掌握的客观真相'),f('knowledge','人物与读者的认知进度','谁先知道？如何揭示？'),field.status]},
 foreshadow:{name:'伏笔管理',icon:'⌖',desc:'埋下的每一条线索，都有可追溯的去向。',fields:[field.title,field.body,f('plant','埋设位置','第几章、哪个场景','input'),f('interpretation','表层解释或误导','初见时读者如何理解？'),f('reveal','回收位置','第几章、哪个节点','input'),f('payoff','真实含义与回收结果','回看时哪些细节成立？'),field.people,f('status','回收状态','','select',['待埋设','已埋设','已回收'])]},
 outline:{name:'章节细纲',icon:'▥',desc:'让每一章都有行动、结果，以及继续发生的理由。',fields:[field.title,f('volume','所属卷','例如：第一卷 · 异常','input'),f('act','所属阶段','','select',[]),f('tag','章节编号或范围','例如：第 1 章','input'),f('pov','视角人物','','input'),f('time','时间','','input'),f('place','地点','','input'),f('goal','本章目标','人物想完成什么？'),f('obstacle','主要阻碍','规则、资源还是他人的选择？'),field.body,f('result','结果与代价','行动改变了什么？'),f('information','新信息与关系变化','人物和读者分别知道了什么？'),f('clues','伏笔埋设／回收','对应伏笔名称'),f('next','对后续情节的影响','为什么必须继续行动？'),field.people,field.status]}
};
const acts=s=>s.structure==='起承转合'?['起','承','转','合']:s.structure==='科幻五阶段'?['异常出现','规则确认','方案竞争','认知翻转','最终抉择']:['开端','发展','结局'];
function normalize(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('草稿结构无效');if(typeof raw.title!=='string'||!raw.title.trim())throw Error('缺少作品名称');if(!['三幕式','起承转合','科幻五阶段'].includes(raw.structure))throw Error('不支持的故事结构');const s={};for(const k of ['title','genre','premise','structure','mode']){if(raw[k]!==undefined&&typeof raw[k]!=='string')throw Error('作品字段无效');s[k]=raw[k]||''}s.mode=s.mode==='科幻'?'科幻':'通用';for(const[k,v]of Object.entries(sections)){const input=raw[k]??(v.single?{}:[]);if(v.single){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('设定字段无效');s[k]={};for(const f of v.fields){if(input[f.key]!==undefined&&typeof input[f.key]!=='string')throw Error('字段必须是文字');s[k][f.key]=input[f.key]||''}}else{if(!Array.isArray(input)||input.length>1000)throw Error('条目数量或格式无效');s[k]=input.map(x=>{if(!x||typeof x!=='object'||typeof x.title!=='string'||Object.values(x).some(v=>typeof v!=='string'))throw Error('条目格式无效');const y={id:crypto.randomUUID()};for(const f of v.fields)y[f.key]=x[f.key]||'';if(k==='outline'&&!acts(s).includes(y.act))throw Error('章节阶段不匹配');return y})}}return s}
function makeStory(d){const s=normalize({...d,overview:{},synopsis:{}});s.outline=acts(s).map((a,i)=>({id:crypto.randomUUID(),title:a+' · 待构思',act:a,tag:'第 '+(i+1)+' 章',body:'',status:'待完善'}));return s}
function markdown(s){let t=`# ${s.title}\n\n题材：${s.genre}\n\n模式：${s.mode} / ${s.structure}\n\n故事核心：${s.premise}\n`;for(const[k,v]of Object.entries(sections)){t+='\n## '+v.name+'\n';const items=v.single?[s[k]]:s[k];for(const x of items){if(!v.single)t+='\n### '+x.title+'\n';for(const f of v.fields)if(f.key!=='title'&&x[f.key])t+='\n**'+f.label+'**\n\n'+x[f.key]+'\n'}}return t}
root.StoryModel={sections,acts,normalize,makeStory,markdown};
})(typeof window==='undefined'?globalThis:window);
